name: Build and Test Backends

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-test-face:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Free Disk Space (before build)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/share/chromium /usr/local/.ghcup /usr/share/swift /opt/hostedtoolcache/swift
          sudo rm -rf /usr/local/lib/node_modules /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby
          docker system prune --all --force --volumes
          sudo apt-get autoremove -y
          sudo apt-get clean
          pip cache purge || true
          df -h

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Face Docker image
        run: |
          docker build -t face-backend -f backends/face/Dockerfile.face backends/face

      - name: Run Face Backend Tests
        run: |
          docker run --rm face-backend python3 face_main.py --run-tests

      - name: Push Face Backend image
        run: |
          IMAGE_NAME=spruceemma/face-backend
          docker tag face-backend $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Free Disk Space (after tests)
        if: always()
        run: |
          docker system prune --all --force --volumes
          sudo apt-get autoremove -y
          sudo apt-get clean
          pip cache purge || true
          df -h

  build-and-test-voice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Free Disk Space (before build)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/share/chromium /usr/local/.ghcup /usr/share/swift /opt/hostedtoolcache/swift
          sudo rm -rf /usr/local/lib/node_modules /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby
          docker system prune --all --force --volumes
          sudo apt-get autoremove -y
          sudo apt-get clean
          pip cache purge || true
          df -h

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Voice Docker image
        run: |
          docker build -t voice-backend -f backends/voice/Dockerfile.voice backends/voice

      - name: Run Voice Backend Tests
        run: |
          docker run --rm voice-backend python3 voice_main.py --run-tests

      - name: Push Voice Backend image
        run: |
          IMAGE_NAME=spruceemma/voice-backend
          docker tag voice-backend $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Free Disk Space (after tests)
        if: always()
        run: |
          docker system prune --all --force --volumes
          sudo apt-get autoremove -y
          sudo apt-get clean
          pip cache purge || true
          df -h
