name: Release Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.backend }}-${{ matrix.runner }}-${{ matrix.device }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        backend: [face, voice]
        device: [cpu]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r backends/${{ matrix.backend }}/requirements.txt
          pip install pyinstaller

      - name: Package backend
        run: |
          python scripts/package_zip.py \
            --backend ${{ matrix.backend }} \
            --device ${{ matrix.device }} \
            --os ${{ matrix.runner }} \
            --version ${{ github.ref_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.backend }}-${{ matrix.runner }}-${{ matrix.device }}
          path: build_${{ matrix.backend }}_*_${{ matrix.device }}/package/*
